### ISSUE TITLE
Duplicate UUID issue when mounting XFS filesystem snapshots

### ISSUE THREAD

**Issue by briansmith0** [linux-system-roles/snapshot#52]
I've been trying out the role with XFS fileystems on RHEL 9, and ran in to an issue with the role failing to mount the snapshot due to the snapshot having a duplicate UUID as the original filesystem.  (see https://access.redhat.com/solutions/5494781 for more details)

However, it looks like the tests_mount.yml test mounts XFS filesystem snapshots, so I'm not sure if I am doing something wrong, and there is a way to avoid this duplicate UUID issue when using the role?  

One of the workarounds covered in that KCS article is to use the "nouuid" mount option, and this seems to work with the role if you define an "options" variable with "nouuid", for example:

```
    snapshot_lvm_set:
      name: snapshot
      volumes:
        - name: app_lv snapshot
          vg: app_vg
          lv: app_lv
          options: nouuid
          mountpoint: /snapshot
          mountpoint_create: true
          percent_space_required: 25
```

However, I don't see the "options" parameter covered in the README.md.  Would this be the best way to mount an XFS snapshot with the role and avoid the duplicate UUID issue?  If so, it might be helpful to document this in the README.md.
